### ISSUE TITLE
pval correction of ranked hypergeometric tests

### ISSUE THREAD

**Issue by lisemangiante** [reimandlab/ActivePathways#13]
Hi all,
First, thank you for keeping this repository very interactive, I really appreciate it. 
I had a question on the method itself this time. If I understand well, for each pathway, your method sets a sub-list of genes from the pathway gene set to perform successive ranked hypergeometric tests. I understand that it selects the minimal p-value from these tests to get the Ppathway metric which is, afterwards, corrected for multiple testing (to take into account the fact that there are k tests for k pathways in the database)  and it gets Qpathway. What you called ranked hypergeometric test is also known as mHG test (minimum hypergeometric test) for which the resulting p-values are always corrected afterwards. Thus, I have the feeling that, even if you performed a correction on Ppathway, the damage has already been done since a correction would be necessary just after generating the mHG p-values and so before the identification of Ppathway and its correction for multiple testing. I guess it would not change the choice of the p-value representing Ppathway but it would change its value and so the final value of Qpathway which is the one used to identified enriched pathways. Did I miss something? What is the rationale behind your choice?

Thank you so much for your help,
Best,
Lise

**Comment by reimand0** [comment]
Hi Lise, 

Thanks for the discussion and relevant points. The use of unadjusted gene-level p-values from ranked hypergeometric statistic (mHG) is a conscious choice to enable a pathway analysis of the "long tail" of sub-significant hits. This is a compromise choice between A) the common pathway enrichment approach (FDR for genes, then analyze enriched pathways for genes, then conduct FDR for pathways), and B) the GSEA approach (rank all genes regardless of their statistical significance, then conduct FDR for pathways). The first approach is quite stringent while the second one is likely quite lenient. ActivePathways attempts to find a middle ground of the two approaches.  

By default ActivePathways selects all genes that show nominal (weak) significance as combined p-values (p<0.1) but this parameter can be changed to reflect a proxy of multiple-testing correction. For example, Bonferroni correction would set the threshold to 1/N where N is the number of gene-level tests, thus 5e-5. 

I hope this answers your questions. 

bestm
Jüri

**Comment by lisemangiante** [comment]
Hi Jüri, 
Thank you for your quick reply and for the explanation. Maybe I missed it but did you test somehow the effect of pathway size on the enrichment results of ActivePathway in the case of having gene sets with heterogeneous size? Since there is no correction on these p-values, don’t you think that pathways containing more genes (and so with greater chance to get smaller p-values by chance) can be more often significantly enriched regarding the others?
Thank you again for the discussion!
Best,
Lise

**Comment by reimand0** [comment]
Hi Lise, 

you are right, larger pathways (gene sets) are naturally better powered to find signals and this is true for hypergeometric tests as well as other approaches like GSEA that compare numeric values of gene set genes and background genes. For hypergeomterics, this happens because larger gene sets support a wider range of possible values, including more extreme values than expected by chance. In other cases, tests with more samples in them tend to be more sensitive to smaller effect sizes. 

I think this problem is well acknowledged in the field and often addressed by simple tricks like removing gene sets that are very large (say more than 1000 genes). We also recommend this with ActivePathways and have some default filters in place. Also the top terms and corresponding gene sets in Gene Ontology are very general and don't help much with the interpretation of data. Some discussion in this review paper- https://pubmed.ncbi.nlm.nih.gov/30664679/. I hope this makes sense and helps move forward.

best,
Jüri
